name: Python

on: [push, pull_request]

jobs:
  test-panlint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest prettytable colorama coverage six mock
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run unit tests
      run: |
        coverage run --source=panc/src/main/scripts/panlint --omit panc/src/main/scripts/panlint/tests.py panc/src/main/scripts/panlint/tests.py
    - name: Report Coverage
      env:
        TERM: xterm
      run: |
        coverage report
        coverage report --format=markdown >> $GITHUB_STEP_SUMMARY
        # Produce a quick and dirty coloured annotation with numbered lines
        coverage annotate
        awk -v ln=1 '{printf("%4d %s\n", ln++, $0) }' panc/src/main/scripts/panlint/panlint.py,cover |
          sed 's#^\( \+[[:digit:]]\+\) !#'"$(tput setaf 1)"'\1 !#' |
          sed 's#^\( \+[[:digit:]]\+\) >#'"$(tput setaf 2)"'\1 >#' |
          sed 's#^\( \+[[:digit:]]\+\)  #'"$(tput setaf 7)"'\1  #'
